# Generated by Django 3.0.3 on 2020-04-20 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_con',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
