# Generated by Django 3.0.3 on 2020-04-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
    ]
