# Generated by Django 3.0.3 on 2020-04-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_ebooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
    ]
